image: macodigo/hugo-nodejs-macodigo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

job1:
  path: 
  - themes/ghostwriter/
  script:
  - npm install

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

