image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - npm install \themes\ghostwriter\package.json
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

