image: jank1310/hugo-node-docker

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - cd '/builds/daniil.marchenko/marchenko.tech/themes/ghostwriter/'
  - npm install
  - npm build
  - cd '/builds/daniil.marchenko/marchenko.tech/'

pages:
  script:
  - hugo 
  artifacts:
    paths:
    - public
  only:
  - master

