image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - cd \themes\ghostwriter
  - npm install 
  - cd ~
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

