image: macodigo/hugo-nodejs-macodigo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - cd '/builds/daniil.marchenko/marchenko.tech/themes/ghostwriter/'
  - npm install

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

