image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

job1:
  script:
  - cd /themes/ghostwriter
  - npm install

pages:
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

